### PR TITLE
WIP deploy with heroku

### PR DESCRIPTION
**Pull request by jocontreras**
**PT Story:** https://www.pivotaltracker.com/story/show/141591397

**Changes proposed in this PR:**
* Deployed in heroku
* link to heroku: https://photo-market-inc.herokuapp.com/

**What I have learned working on this feature:**
*
screen shot 2017-03-16 at 10 44 04 am
Deploying app to heroku

**Screenshots:**
screen shot 2017-03-16 at 10 44 04 am

### CODE REVIEW

**Review by tochman — CHANGES_REQUESTED** [review]
There are no changes in this pr. ???

**Review by tochman — CHANGES_REQUESTED** [review]
There's no changes in this PR. ???

**Comment by diraulo** [comment]
I showed @jocontreras a different way of setting up automatic deployment from the Heroku dashboard. And as soon as the next feature is merged in and deployed we can close this PR since it's not needed anymore.

**Comment by tochman** [comment]
skarmavbild 2017-03-16 kl 12 17 04

**Comment by AmberWilkie** [comment]
Someone should check the heroku logs: `heroku logs -t` to see what is going on with that error. If you don't have any images in the database, that may be the problem.

**Comment by jocontreras** [comment]
It is fine now after doing  ```$heroku run rake db:migrate```

**Review by diraulo — CHANGES_REQUESTED** [review]
@jocontreras We need to be able to run the migration after the deployment. So once you add that to, we can merge this.

Also once it's merged don't forget to disable the automatic deploy on Heroku

**Comment by tochman** [comment]
Closing this.

**Comment by diraulo** [comment]
@tochman any specific reason why this was closed?

**Comment by tochman** [comment]
The team said it should be @diraulo

**Comment by diraulo** [comment]
👍  okay. The only shortcoming of the current deployment method is that someone will have to manually run the migrations after a deployment. That's why I asked @jocontreras to set this up. But if it was a common agreement then it's all good :)

**Comment by tochman** [comment]
I'm happy to reopen this but the team was not clear on if this was still relevant.

**Pull request closed without merging**
