### PR TITLE
Add Index page

### PR DESCRIPTION
**Pull request by casperjureskog**
**PT Story:** https://www.pivotaltracker.com/story/show/141596947

**Changes proposed in this PR:**

* Add featrue test for index page
* Added landing conrtoller and index in view.

**What I have learned working on this feature:**
That it was surpricingly easy

@diraulo @tochman @AmberWilkie

### CODE REVIEW

**Comment by tochman** [comment]
I need the coveralls PR merge first.

**Comment by tochman** [comment]
@casperjureskog You need to update the tasks on PT as you move along and implement them.

**Comment by AmberWilkie** [comment]
I'm just merging this, there's nothing wrong with it.

**Comment by tochman** [comment]
There is. Please update https://www.pivotaltracker.com/story/show/141596947

**Pull request merged**
